// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/llm-connection": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "llm-connection"
                ],
                "summary": "List LlmConnections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/LLMConnectionsPage"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "llm-connection"
                ],
                "summary": "Create a LlmConnection",
                "parameters": [
                    {
                        "description": "payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateLlmConnectionDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/LLMConnectionResponse"
                        }
                    }
                }
            }
        },
        "/llm-connection/registry": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Lists the available LLM provider drivers on registry.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "llm-connection"
                ],
                "summary": "List LLM providers registry",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/LLMProviderRegistry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/Error"
                        }
                    }
                }
            }
        },
        "/llm-connection/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "llm-connection"
                ],
                "summary": "Get a LlmConnection by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LlmConnection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/LLMConnectionResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "llm-connection"
                ],
                "summary": "Update a LlmConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LlmConnection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "partial payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateLlmConnectionDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "tags": [
                    "llm-connection"
                ],
                "summary": "Delete a LlmConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "LlmConnection ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/system/info": {
            "get": {
                "description": "Returns application system information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/InfoDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateLlmConnectionDTO": {
            "type": "object",
            "required": [
                "config",
                "name",
                "provider"
            ],
            "properties": {
                "config": {
                    "$ref": "#/definitions/JSONMap"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "provider": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "InfoDTO": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string"
                }
            }
        },
        "JSONMap": {
            "type": "object",
            "additionalProperties": {}
        },
        "LLMConnectionResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/JSONMap"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "LLMConnectionsPage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/LlmConnection"
                    }
                },
                "skip": {
                    "type": "integer"
                },
                "take": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "LLMProviderRegistry": {
            "type": "object",
            "required": [
                "description",
                "key",
                "name"
            ],
            "properties": {
                "configuration_schema": {
                    "$ref": "#/definitions/JSONMap"
                },
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "LlmConnection": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/JSONMap"
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "UpdateLlmConnectionDTO": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/JSONMap"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255
                },
                "provider": {
                    "type": "string",
                    "maxLength": 255
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "snipets API",
	Description:      "API for the snipets platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
