basePath: /api
definitions:
  CreateLlmConnectionDTO:
    properties:
      config:
        $ref: '#/definitions/JSONMap'
      enabled:
        type: boolean
      name:
        maxLength: 255
        type: string
      provider:
        maxLength: 255
        type: string
    required:
    - config
    - name
    - provider
    type: object
  Error:
    properties:
      details:
        additionalProperties: {}
        type: object
      message:
        type: string
      statusCode:
        type: integer
    type: object
  InfoDTO:
    properties:
      version:
        type: string
    type: object
  JSONMap:
    additionalProperties: {}
    type: object
  LLMConnectionResponse:
    properties:
      config:
        $ref: '#/definitions/JSONMap'
      created_at:
        type: string
      enabled:
        type: boolean
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      updated_at:
        type: string
    type: object
  LLMConnectionsPage:
    properties:
      data:
        items:
          $ref: '#/definitions/LlmConnection'
        type: array
      skip:
        type: integer
      take:
        type: integer
      total:
        type: integer
    type: object
  LLMProviderRegistry:
    properties:
      configuration_schema:
        $ref: '#/definitions/JSONMap'
      description:
        type: string
      icon:
        type: string
      key:
        type: string
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    required:
    - description
    - key
    - name
    type: object
  LlmConnection:
    properties:
      config:
        $ref: '#/definitions/JSONMap'
      created_at:
        type: string
      enabled:
        type: boolean
      id:
        type: string
      name:
        type: string
      provider:
        type: string
      updated_at:
        type: string
    type: object
  UpdateLlmConnectionDTO:
    properties:
      config:
        $ref: '#/definitions/JSONMap'
      enabled:
        type: boolean
      name:
        maxLength: 255
        type: string
      provider:
        maxLength: 255
        type: string
    type: object
info:
  contact: {}
  description: API for the snipets platform.
  title: snipets API
  version: "1.0"
paths:
  /llm-connection:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LLMConnectionsPage'
      summary: List LlmConnections
      tags:
      - llm-connection
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/CreateLlmConnectionDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/LLMConnectionResponse'
      summary: Create a LlmConnection
      tags:
      - llm-connection
  /llm-connection/{id}:
    delete:
      parameters:
      - description: LlmConnection ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: Delete a LlmConnection
      tags:
      - llm-connection
    get:
      parameters:
      - description: LlmConnection ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/LLMConnectionResponse'
      summary: Get a LlmConnection by ID
      tags:
      - llm-connection
    put:
      consumes:
      - application/json
      parameters:
      - description: LlmConnection ID
        in: path
        name: id
        required: true
        type: string
      - description: partial payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/UpdateLlmConnectionDTO'
      responses:
        "204":
          description: No Content
      summary: Update a LlmConnection
      tags:
      - llm-connection
  /llm-connection/registry:
    get:
      description: Lists the available LLM provider drivers on registry.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/LLMProviderRegistry'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
      security:
      - BasicAuth: []
      summary: List LLM providers registry
      tags:
      - llm-connection
  /system/info:
    get:
      description: Returns application system information.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/InfoDTO'
      summary: Get system info
      tags:
      - system
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-API-Key
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
