version: 2

project_name: snipet

before:
  hooks:
    - go mod tidy
    - sh -c "cd web && pnpm install --frozen-lockfile && pnpm build"

builds:
  - id: api
    main: ./cmd/api
    binary: snipet
    tags:
      - web
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/usesnipet/snipet/version.Version={{ .Version }}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - migrations
      - docs/swagger

snapshot:
  version_template: "{{ .ShortCommit }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

dockers_v2:
  - id: api
    ids: [api]
    dockerfile: Dockerfile.goreleaser
    images:
      - docker.io/snipet/snipet-go
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - migrations
      - docs/swagger
