FROM alpine:3.21

WORKDIR /app

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/snipet ./api
COPY migrations ./migrations
COPY docs/swagger ./docs/swagger

USER nobody

EXPOSE 8080

ENV ENV=production

ENTRYPOINT ["./api"]
