/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { DeleteUsersIdMutationResponse, DeleteUsersIdPathParams, DeleteUsersId400, DeleteUsersId500 } from "../types/DeleteUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getDeleteUsersIdUrl(id: DeleteUsersIdPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/users/${id}` as const }
  return res
}

/**
 * @description Delete a user by ID.
 * @summary Delete user by ID
 * {@link /users/:id}
 */
export async function deleteUsersId(id: DeleteUsersIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, unknown>({ method : "DELETE", url : getDeleteUsersIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}