/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetUsersQueryResponse, GetUsersQueryParams, GetUsers400, GetUsers500 } from "../types/GetUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetUsersUrl() {
  const res = { method: 'GET', url: `/api/users` as const }
  return res
}

/**
 * @description Return a list of users with pagination and optional filters.
 * @summary Find all users
 * {@link /users}
 */
export async function getUsers(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUsersQueryResponse, ResponseErrorConfig<GetUsers400 | GetUsers500>, unknown>({ method : "GET", url : getGetUsersUrl().url.toString(), params, ... requestConfig })
  return res.data
}