/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetUsersIdQueryResponse, GetUsersIdPathParams, GetUsersId500 } from "../types/GetUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetUsersIdUrl(id: GetUsersIdPathParams["id"]) {
  const res = { method: 'GET', url: `/api/users/${id}` as const }
  return res
}

/**
 * @description Return a user by ID.
 * @summary Find user by ID
 * {@link /users/:id}
 */
export async function getUsersId(id: GetUsersIdPathParams["id"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetUsersIdQueryResponse, ResponseErrorConfig<GetUsersId500>, unknown>({ method : "GET", url : getGetUsersIdUrl(id).url.toString(), ... requestConfig })
  return res.data
}