/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { PostUsersMutationRequest, PostUsersMutationResponse, PostUsers400, PostUsers500 } from "../types/PostUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getPostUsersUrl() {
  const res = { method: 'POST', url: `/api/users` as const }
  return res
}

/**
 * @description Create a new user.
 * @summary Create user
 * {@link /users}
 */
export async function postUsers(data: PostUsersMutationRequest, config: Partial<RequestConfig<PostUsersMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, PostUsersMutationRequest>({ method : "POST", url : getPostUsersUrl().url.toString(), data : requestData, ... requestConfig })
  return res.data
}