/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { PutUsersIdMutationRequest, PutUsersIdMutationResponse, PutUsersIdPathParams, PutUsersId400, PutUsersId500 } from "../types/PutUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getPutUsersIdUrl(id: PutUsersIdPathParams["id"]) {
  const res = { method: 'PUT', url: `/api/users/${id}` as const }
  return res
}

/**
 * @description Update a user by ID.
 * @summary Update user by ID
 * {@link /users/:id}
 */
export async function putUsersId(id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest, config: Partial<RequestConfig<PutUsersIdMutationRequest>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, PutUsersIdMutationRequest>({ method : "PUT", url : getPutUsersIdUrl(id).url.toString(), data : requestData, ... requestConfig })
  return res.data
}