/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const modelRole = {
    RoleUser: "user",
    RoleAdmin: "admin"
} as const;

export type ModelRoleEnumKey = (typeof modelRole)[keyof typeof modelRole];

export type ModelRole = ModelRoleEnumKey;