/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRole } from "./Role.ts";

export type ModelUser = {
    /**
     * @type string | undefined
    */
    createdAt?: string;
    /**
     * @type string | undefined
    */
    email?: string;
    /**
     * @type string | undefined
    */
    id?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    password?: string;
    /**
     * @type string | undefined
    */
    role?: ModelRole;
    /**
     * @type string | undefined
    */
    updatedAt?: string;
};