// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIAgentRunRepository creates a new instance of MockIAgentRunRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAgentRunRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAgentRunRepository {
	mock := &MockIAgentRunRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAgentRunRepository is an autogenerated mock type for the IAgentRunRepository type
type MockIAgentRunRepository struct {
	mock.Mock
}

type MockIAgentRunRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAgentRunRepository) EXPECT() *MockIAgentRunRepository_Expecter {
	return &MockIAgentRunRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) Create(ctx context.Context, model1 *model.AgentRun) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AgentRun) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentRunRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAgentRunRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.AgentRun
func (_e *MockIAgentRunRepository_Expecter) Create(ctx any, model1 any) *MockIAgentRunRepository_Create_Call {
	return &MockIAgentRunRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIAgentRunRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.AgentRun)) *MockIAgentRunRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AgentRun
		if args[1] != nil {
			arg1 = args[1].(*model.AgentRun)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_Create_Call) Return(err error) *MockIAgentRunRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentRunRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.AgentRun) error) *MockIAgentRunRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentRunRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIAgentRunRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAgentRunRepository_Expecter) DeleteByID(ctx any, id any) *MockIAgentRunRepository_DeleteByID_Call {
	return &MockIAgentRunRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIAgentRunRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIAgentRunRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_DeleteByID_Call) Return(err error) *MockIAgentRunRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentRunRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAgentRunRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FailAllRunning provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) FailAllRunning(ctx context.Context, errMsg string) (int64, error) {
	ret := _mock.Called(ctx, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for FailAllRunning")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, errMsg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, errMsg)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, errMsg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentRunRepository_FailAllRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailAllRunning'
type MockIAgentRunRepository_FailAllRunning_Call struct {
	*mock.Call
}

// FailAllRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - errMsg string
func (_e *MockIAgentRunRepository_Expecter) FailAllRunning(ctx any, errMsg any) *MockIAgentRunRepository_FailAllRunning_Call {
	return &MockIAgentRunRepository_FailAllRunning_Call{Call: _e.mock.On("FailAllRunning", ctx, errMsg)}
}

func (_c *MockIAgentRunRepository_FailAllRunning_Call) Run(run func(ctx context.Context, errMsg string)) *MockIAgentRunRepository_FailAllRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_FailAllRunning_Call) Return(n int64, err error) *MockIAgentRunRepository_FailAllRunning_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIAgentRunRepository_FailAllRunning_Call) RunAndReturn(run func(ctx context.Context, errMsg string) (int64, error)) *MockIAgentRunRepository_FailAllRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) Filter(ctx context.Context, filter1 *filter.Options[model.AgentRun]) (*page.Paginated[model.AgentRun], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.AgentRun]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.AgentRun]) (*page.Paginated[model.AgentRun], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.AgentRun]) *page.Paginated[model.AgentRun]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.AgentRun])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.AgentRun]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentRunRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIAgentRunRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.AgentRun]
func (_e *MockIAgentRunRepository_Expecter) Filter(ctx any, filter1 any) *MockIAgentRunRepository_Filter_Call {
	return &MockIAgentRunRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIAgentRunRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.AgentRun])) *MockIAgentRunRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.AgentRun]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.AgentRun])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_Filter_Call) Return(paginated *page.Paginated[model.AgentRun], err error) *MockIAgentRunRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIAgentRunRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.AgentRun]) (*page.Paginated[model.AgentRun], error)) *MockIAgentRunRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) FindByID(ctx context.Context, id string) (*model.AgentRun, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.AgentRun
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AgentRun, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AgentRun); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentRun)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentRunRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAgentRunRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAgentRunRepository_Expecter) FindByID(ctx any, id any) *MockIAgentRunRepository_FindByID_Call {
	return &MockIAgentRunRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAgentRunRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIAgentRunRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_FindByID_Call) Return(agentRun *model.AgentRun, err error) *MockIAgentRunRepository_FindByID_Call {
	_c.Call.Return(agentRun, err)
	return _c
}

func (_c *MockIAgentRunRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.AgentRun, error)) *MockIAgentRunRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasRunning provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) HasRunning(ctx context.Context, sessionID string) (bool, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for HasRunning")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentRunRepository_HasRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRunning'
type MockIAgentRunRepository_HasRunning_Call struct {
	*mock.Call
}

// HasRunning is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockIAgentRunRepository_Expecter) HasRunning(ctx any, sessionID any) *MockIAgentRunRepository_HasRunning_Call {
	return &MockIAgentRunRepository_HasRunning_Call{Call: _e.mock.On("HasRunning", ctx, sessionID)}
}

func (_c *MockIAgentRunRepository_HasRunning_Call) Run(run func(ctx context.Context, sessionID string)) *MockIAgentRunRepository_HasRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_HasRunning_Call) Return(b bool, err error) *MockIAgentRunRepository_HasRunning_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIAgentRunRepository_HasRunning_Call) RunAndReturn(run func(ctx context.Context, sessionID string) (bool, error)) *MockIAgentRunRepository_HasRunning_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIAgentRunRepository
func (_mock *MockIAgentRunRepository) UpdateByID(ctx context.Context, id string, model1 *model.AgentRun) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.AgentRun) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentRunRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIAgentRunRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.AgentRun
func (_e *MockIAgentRunRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIAgentRunRepository_UpdateByID_Call {
	return &MockIAgentRunRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIAgentRunRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.AgentRun)) *MockIAgentRunRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.AgentRun
		if args[2] != nil {
			arg2 = args[2].(*model.AgentRun)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAgentRunRepository_UpdateByID_Call) Return(err error) *MockIAgentRunRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentRunRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.AgentRun) error) *MockIAgentRunRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
