// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIAgentMessageRepository creates a new instance of MockIAgentMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAgentMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAgentMessageRepository {
	mock := &MockIAgentMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIAgentMessageRepository is an autogenerated mock type for the IAgentMessageRepository type
type MockIAgentMessageRepository struct {
	mock.Mock
}

type MockIAgentMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAgentMessageRepository) EXPECT() *MockIAgentMessageRepository_Expecter {
	return &MockIAgentMessageRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) Create(ctx context.Context, model1 *model.AgentMessage) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AgentMessage) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentMessageRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAgentMessageRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.AgentMessage
func (_e *MockIAgentMessageRepository_Expecter) Create(ctx any, model1 any) *MockIAgentMessageRepository_Create_Call {
	return &MockIAgentMessageRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIAgentMessageRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.AgentMessage)) *MockIAgentMessageRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AgentMessage
		if args[1] != nil {
			arg1 = args[1].(*model.AgentMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_Create_Call) Return(err error) *MockIAgentMessageRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentMessageRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.AgentMessage) error) *MockIAgentMessageRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentMessageRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIAgentMessageRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAgentMessageRepository_Expecter) DeleteByID(ctx any, id any) *MockIAgentMessageRepository_DeleteByID_Call {
	return &MockIAgentMessageRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIAgentMessageRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIAgentMessageRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_DeleteByID_Call) Return(err error) *MockIAgentMessageRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentMessageRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIAgentMessageRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) Filter(ctx context.Context, filter1 *filter.Options[model.AgentMessage]) (*page.Paginated[model.AgentMessage], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.AgentMessage]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.AgentMessage]) (*page.Paginated[model.AgentMessage], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.AgentMessage]) *page.Paginated[model.AgentMessage]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.AgentMessage])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.AgentMessage]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentMessageRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIAgentMessageRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.AgentMessage]
func (_e *MockIAgentMessageRepository_Expecter) Filter(ctx any, filter1 any) *MockIAgentMessageRepository_Filter_Call {
	return &MockIAgentMessageRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIAgentMessageRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.AgentMessage])) *MockIAgentMessageRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.AgentMessage]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.AgentMessage])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_Filter_Call) Return(paginated *page.Paginated[model.AgentMessage], err error) *MockIAgentMessageRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIAgentMessageRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.AgentMessage]) (*page.Paginated[model.AgentMessage], error)) *MockIAgentMessageRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) FindByID(ctx context.Context, id string) (*model.AgentMessage, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.AgentMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AgentMessage, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AgentMessage); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AgentMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentMessageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAgentMessageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIAgentMessageRepository_Expecter) FindByID(ctx any, id any) *MockIAgentMessageRepository_FindByID_Call {
	return &MockIAgentMessageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIAgentMessageRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIAgentMessageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_FindByID_Call) Return(agentMessage *model.AgentMessage, err error) *MockIAgentMessageRepository_FindByID_Call {
	_c.Call.Return(agentMessage, err)
	return _c
}

func (_c *MockIAgentMessageRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.AgentMessage, error)) *MockIAgentMessageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRunAfter provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) ListByRunAfter(ctx context.Context, runID string, afterID int64) ([]model.AgentMessage, error) {
	ret := _mock.Called(ctx, runID, afterID)

	if len(ret) == 0 {
		panic("no return value specified for ListByRunAfter")
	}

	var r0 []model.AgentMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) ([]model.AgentMessage, error)); ok {
		return returnFunc(ctx, runID, afterID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) []model.AgentMessage); ok {
		r0 = returnFunc(ctx, runID, afterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AgentMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, runID, afterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentMessageRepository_ListByRunAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByRunAfter'
type MockIAgentMessageRepository_ListByRunAfter_Call struct {
	*mock.Call
}

// ListByRunAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - afterID int64
func (_e *MockIAgentMessageRepository_Expecter) ListByRunAfter(ctx any, runID any, afterID any) *MockIAgentMessageRepository_ListByRunAfter_Call {
	return &MockIAgentMessageRepository_ListByRunAfter_Call{Call: _e.mock.On("ListByRunAfter", ctx, runID, afterID)}
}

func (_c *MockIAgentMessageRepository_ListByRunAfter_Call) Run(run func(ctx context.Context, runID string, afterID int64)) *MockIAgentMessageRepository_ListByRunAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_ListByRunAfter_Call) Return(agentMessages []model.AgentMessage, err error) *MockIAgentMessageRepository_ListByRunAfter_Call {
	_c.Call.Return(agentMessages, err)
	return _c
}

func (_c *MockIAgentMessageRepository_ListByRunAfter_Call) RunAndReturn(run func(ctx context.Context, runID string, afterID int64) ([]model.AgentMessage, error)) *MockIAgentMessageRepository_ListByRunAfter_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySession provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) ListBySession(ctx context.Context, sessionID string) ([]model.AgentMessage, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySession")
	}

	var r0 []model.AgentMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.AgentMessage, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.AgentMessage); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AgentMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAgentMessageRepository_ListBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySession'
type MockIAgentMessageRepository_ListBySession_Call struct {
	*mock.Call
}

// ListBySession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockIAgentMessageRepository_Expecter) ListBySession(ctx any, sessionID any) *MockIAgentMessageRepository_ListBySession_Call {
	return &MockIAgentMessageRepository_ListBySession_Call{Call: _e.mock.On("ListBySession", ctx, sessionID)}
}

func (_c *MockIAgentMessageRepository_ListBySession_Call) Run(run func(ctx context.Context, sessionID string)) *MockIAgentMessageRepository_ListBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_ListBySession_Call) Return(agentMessages []model.AgentMessage, err error) *MockIAgentMessageRepository_ListBySession_Call {
	_c.Call.Return(agentMessages, err)
	return _c
}

func (_c *MockIAgentMessageRepository_ListBySession_Call) RunAndReturn(run func(ctx context.Context, sessionID string) ([]model.AgentMessage, error)) *MockIAgentMessageRepository_ListBySession_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIAgentMessageRepository
func (_mock *MockIAgentMessageRepository) UpdateByID(ctx context.Context, id string, model1 *model.AgentMessage) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.AgentMessage) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAgentMessageRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIAgentMessageRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.AgentMessage
func (_e *MockIAgentMessageRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIAgentMessageRepository_UpdateByID_Call {
	return &MockIAgentMessageRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIAgentMessageRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.AgentMessage)) *MockIAgentMessageRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.AgentMessage
		if args[2] != nil {
			arg2 = args[2].(*model.AgentMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAgentMessageRepository_UpdateByID_Call) Return(err error) *MockIAgentMessageRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAgentMessageRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.AgentMessage) error) *MockIAgentMessageRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
