// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockILlmConnectionRepository creates a new instance of MockILlmConnectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILlmConnectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILlmConnectionRepository {
	mock := &MockILlmConnectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockILlmConnectionRepository is an autogenerated mock type for the ILlmConnectionRepository type
type MockILlmConnectionRepository struct {
	mock.Mock
}

type MockILlmConnectionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockILlmConnectionRepository) EXPECT() *MockILlmConnectionRepository_Expecter {
	return &MockILlmConnectionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockILlmConnectionRepository
func (_mock *MockILlmConnectionRepository) Create(ctx context.Context, model1 *model.LlmConnection) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.LlmConnection) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILlmConnectionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockILlmConnectionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.LlmConnection
func (_e *MockILlmConnectionRepository_Expecter) Create(ctx any, model1 any) *MockILlmConnectionRepository_Create_Call {
	return &MockILlmConnectionRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockILlmConnectionRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.LlmConnection)) *MockILlmConnectionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.LlmConnection
		if args[1] != nil {
			arg1 = args[1].(*model.LlmConnection)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILlmConnectionRepository_Create_Call) Return(err error) *MockILlmConnectionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILlmConnectionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.LlmConnection) error) *MockILlmConnectionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockILlmConnectionRepository
func (_mock *MockILlmConnectionRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILlmConnectionRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockILlmConnectionRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockILlmConnectionRepository_Expecter) DeleteByID(ctx any, id any) *MockILlmConnectionRepository_DeleteByID_Call {
	return &MockILlmConnectionRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockILlmConnectionRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockILlmConnectionRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILlmConnectionRepository_DeleteByID_Call) Return(err error) *MockILlmConnectionRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILlmConnectionRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockILlmConnectionRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockILlmConnectionRepository
func (_mock *MockILlmConnectionRepository) Filter(ctx context.Context, filter1 *filter.Options[model.LlmConnection]) (*page.Paginated[model.LlmConnection], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.LlmConnection]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.LlmConnection]) (*page.Paginated[model.LlmConnection], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.LlmConnection]) *page.Paginated[model.LlmConnection]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.LlmConnection])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.LlmConnection]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILlmConnectionRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockILlmConnectionRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.LlmConnection]
func (_e *MockILlmConnectionRepository_Expecter) Filter(ctx any, filter1 any) *MockILlmConnectionRepository_Filter_Call {
	return &MockILlmConnectionRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockILlmConnectionRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.LlmConnection])) *MockILlmConnectionRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.LlmConnection]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.LlmConnection])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILlmConnectionRepository_Filter_Call) Return(paginated *page.Paginated[model.LlmConnection], err error) *MockILlmConnectionRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockILlmConnectionRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.LlmConnection]) (*page.Paginated[model.LlmConnection], error)) *MockILlmConnectionRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockILlmConnectionRepository
func (_mock *MockILlmConnectionRepository) FindByID(ctx context.Context, id string) (*model.LlmConnection, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.LlmConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.LlmConnection, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.LlmConnection); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LlmConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockILlmConnectionRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockILlmConnectionRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockILlmConnectionRepository_Expecter) FindByID(ctx any, id any) *MockILlmConnectionRepository_FindByID_Call {
	return &MockILlmConnectionRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockILlmConnectionRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockILlmConnectionRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockILlmConnectionRepository_FindByID_Call) Return(llmConnection *model.LlmConnection, err error) *MockILlmConnectionRepository_FindByID_Call {
	_c.Call.Return(llmConnection, err)
	return _c
}

func (_c *MockILlmConnectionRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.LlmConnection, error)) *MockILlmConnectionRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockILlmConnectionRepository
func (_mock *MockILlmConnectionRepository) UpdateByID(ctx context.Context, id string, model1 *model.LlmConnection) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.LlmConnection) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockILlmConnectionRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockILlmConnectionRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.LlmConnection
func (_e *MockILlmConnectionRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockILlmConnectionRepository_UpdateByID_Call {
	return &MockILlmConnectionRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockILlmConnectionRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.LlmConnection)) *MockILlmConnectionRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.LlmConnection
		if args[2] != nil {
			arg2 = args[2].(*model.LlmConnection)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockILlmConnectionRepository_UpdateByID_Call) Return(err error) *MockILlmConnectionRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockILlmConnectionRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.LlmConnection) error) *MockILlmConnectionRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
