// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIMcpServerRepository creates a new instance of MockIMcpServerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIMcpServerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIMcpServerRepository {
	mock := &MockIMcpServerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIMcpServerRepository is an autogenerated mock type for the IMcpServerRepository type
type MockIMcpServerRepository struct {
	mock.Mock
}

type MockIMcpServerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIMcpServerRepository) EXPECT() *MockIMcpServerRepository_Expecter {
	return &MockIMcpServerRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIMcpServerRepository
func (_mock *MockIMcpServerRepository) Create(ctx context.Context, model1 *model.McpServer) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.McpServer) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMcpServerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIMcpServerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.McpServer
func (_e *MockIMcpServerRepository_Expecter) Create(ctx any, model1 any) *MockIMcpServerRepository_Create_Call {
	return &MockIMcpServerRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIMcpServerRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.McpServer)) *MockIMcpServerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.McpServer
		if args[1] != nil {
			arg1 = args[1].(*model.McpServer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMcpServerRepository_Create_Call) Return(err error) *MockIMcpServerRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMcpServerRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.McpServer) error) *MockIMcpServerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIMcpServerRepository
func (_mock *MockIMcpServerRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMcpServerRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIMcpServerRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMcpServerRepository_Expecter) DeleteByID(ctx any, id any) *MockIMcpServerRepository_DeleteByID_Call {
	return &MockIMcpServerRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIMcpServerRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIMcpServerRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMcpServerRepository_DeleteByID_Call) Return(err error) *MockIMcpServerRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMcpServerRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIMcpServerRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIMcpServerRepository
func (_mock *MockIMcpServerRepository) Filter(ctx context.Context, filter1 *filter.Options[model.McpServer]) (*page.Paginated[model.McpServer], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.McpServer]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.McpServer]) (*page.Paginated[model.McpServer], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.McpServer]) *page.Paginated[model.McpServer]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.McpServer])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.McpServer]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMcpServerRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIMcpServerRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.McpServer]
func (_e *MockIMcpServerRepository_Expecter) Filter(ctx any, filter1 any) *MockIMcpServerRepository_Filter_Call {
	return &MockIMcpServerRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIMcpServerRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.McpServer])) *MockIMcpServerRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.McpServer]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.McpServer])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMcpServerRepository_Filter_Call) Return(paginated *page.Paginated[model.McpServer], err error) *MockIMcpServerRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIMcpServerRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.McpServer]) (*page.Paginated[model.McpServer], error)) *MockIMcpServerRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIMcpServerRepository
func (_mock *MockIMcpServerRepository) FindByID(ctx context.Context, id string) (*model.McpServer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.McpServer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.McpServer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.McpServer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.McpServer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIMcpServerRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIMcpServerRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIMcpServerRepository_Expecter) FindByID(ctx any, id any) *MockIMcpServerRepository_FindByID_Call {
	return &MockIMcpServerRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIMcpServerRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIMcpServerRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIMcpServerRepository_FindByID_Call) Return(mcpServer *model.McpServer, err error) *MockIMcpServerRepository_FindByID_Call {
	_c.Call.Return(mcpServer, err)
	return _c
}

func (_c *MockIMcpServerRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.McpServer, error)) *MockIMcpServerRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIMcpServerRepository
func (_mock *MockIMcpServerRepository) UpdateByID(ctx context.Context, id string, model1 *model.McpServer) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.McpServer) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIMcpServerRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIMcpServerRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.McpServer
func (_e *MockIMcpServerRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIMcpServerRepository_UpdateByID_Call {
	return &MockIMcpServerRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIMcpServerRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.McpServer)) *MockIMcpServerRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.McpServer
		if args[2] != nil {
			arg2 = args[2].(*model.McpServer)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIMcpServerRepository_UpdateByID_Call) Return(err error) *MockIMcpServerRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIMcpServerRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.McpServer) error) *MockIMcpServerRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
