// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/filter"
	"github.com/usesnipet/snipet/internal/model"
	"github.com/usesnipet/snipet/internal/page"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// CountAll provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CountAll(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAll")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CountAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAll'
type MockIUserRepository_CountAll_Call struct {
	*mock.Call
}

// CountAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIUserRepository_Expecter) CountAll(ctx any) *MockIUserRepository_CountAll_Call {
	return &MockIUserRepository_CountAll_Call{Call: _e.mock.On("CountAll", ctx)}
}

func (_c *MockIUserRepository_CountAll_Call) Run(run func(ctx context.Context)) *MockIUserRepository_CountAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CountAll_Call) Return(n int64, err error) *MockIUserRepository_CountAll_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIUserRepository_CountAll_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockIUserRepository_CountAll_Call {
	_c.Call.Return(run)
	return _c
}

// CountByRole provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) CountByRole(ctx context.Context, role model.Role) (int64, error) {
	ret := _mock.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CountByRole")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Role) (int64, error)); ok {
		return returnFunc(ctx, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Role) int64); ok {
		r0 = returnFunc(ctx, role)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Role) error); ok {
		r1 = returnFunc(ctx, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_CountByRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByRole'
type MockIUserRepository_CountByRole_Call struct {
	*mock.Call
}

// CountByRole is a helper method to define mock.On call
//   - ctx context.Context
//   - role model.Role
func (_e *MockIUserRepository_Expecter) CountByRole(ctx any, role any) *MockIUserRepository_CountByRole_Call {
	return &MockIUserRepository_CountByRole_Call{Call: _e.mock.On("CountByRole", ctx, role)}
}

func (_c *MockIUserRepository_CountByRole_Call) Run(run func(ctx context.Context, role model.Role)) *MockIUserRepository_CountByRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Role
		if args[1] != nil {
			arg1 = args[1].(model.Role)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_CountByRole_Call) Return(n int64, err error) *MockIUserRepository_CountByRole_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIUserRepository_CountByRole_Call) RunAndReturn(run func(ctx context.Context, role model.Role) (int64, error)) *MockIUserRepository_CountByRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Create(ctx context.Context, model1 *model.User) error {
	ret := _mock.Called(ctx, model1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = returnFunc(ctx, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model1 *model.User
func (_e *MockIUserRepository_Expecter) Create(ctx any, model1 any) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, model1)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(ctx context.Context, model1 *model.User)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.User
		if args[1] != nil {
			arg1 = args[1].(*model.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(err error) *MockIUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, model1 *model.User) error) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) DeleteByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockIUserRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIUserRepository_Expecter) DeleteByID(ctx any, id any) *MockIUserRepository_DeleteByID_Call {
	return &MockIUserRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockIUserRepository_DeleteByID_Call) Run(run func(ctx context.Context, id string)) *MockIUserRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_DeleteByID_Call) Return(err error) *MockIUserRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockIUserRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Filter(ctx context.Context, filter1 *filter.Options[model.User]) (*page.Paginated[model.User], error) {
	ret := _mock.Called(ctx, filter1)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 *page.Paginated[model.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.User]) (*page.Paginated[model.User], error)); ok {
		return returnFunc(ctx, filter1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *filter.Options[model.User]) *page.Paginated[model.User]); ok {
		r0 = returnFunc(ctx, filter1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*page.Paginated[model.User])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *filter.Options[model.User]) error); ok {
		r1 = returnFunc(ctx, filter1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockIUserRepository_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 *filter.Options[model.User]
func (_e *MockIUserRepository_Expecter) Filter(ctx any, filter1 any) *MockIUserRepository_Filter_Call {
	return &MockIUserRepository_Filter_Call{Call: _e.mock.On("Filter", ctx, filter1)}
}

func (_c *MockIUserRepository_Filter_Call) Run(run func(ctx context.Context, filter1 *filter.Options[model.User])) *MockIUserRepository_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *filter.Options[model.User]
		if args[1] != nil {
			arg1 = args[1].(*filter.Options[model.User])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Filter_Call) Return(paginated *page.Paginated[model.User], err error) *MockIUserRepository_Filter_Call {
	_c.Call.Return(paginated, err)
	return _c
}

func (_c *MockIUserRepository_Filter_Call) RunAndReturn(run func(ctx context.Context, filter1 *filter.Options[model.User]) (*page.Paginated[model.User], error)) *MockIUserRepository_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindByID(ctx context.Context, id string) (*model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockIUserRepository_Expecter) FindByID(ctx any, id any) *MockIUserRepository_FindByID_Call {
	return &MockIUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockIUserRepository_FindByID_Call) Run(run func(ctx context.Context, id string)) *MockIUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FindByID_Call) Return(user *model.User, err error) *MockIUserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.User, error)) *MockIUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) FindByUsername(ctx context.Context, username string) (*model.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockIUserRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) FindByUsername(ctx any, username any) *MockIUserRepository_FindByUsername_Call {
	return &MockIUserRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockIUserRepository_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) Return(user *model.User, err error) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*model.User, error)) *MockIUserRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) UpdateByID(ctx context.Context, id string, model1 *model.User) error {
	ret := _mock.Called(ctx, id, model1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.User) error); ok {
		r0 = returnFunc(ctx, id, model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockIUserRepository_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - model1 *model.User
func (_e *MockIUserRepository_Expecter) UpdateByID(ctx any, id any, model1 any) *MockIUserRepository_UpdateByID_Call {
	return &MockIUserRepository_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, model1)}
}

func (_c *MockIUserRepository_UpdateByID_Call) Run(run func(ctx context.Context, id string, model1 *model.User)) *MockIUserRepository_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.User
		if args[2] != nil {
			arg2 = args[2].(*model.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_UpdateByID_Call) Return(err error) *MockIUserRepository_UpdateByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_UpdateByID_Call) RunAndReturn(run func(ctx context.Context, id string, model1 *model.User) error) *MockIUserRepository_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}
