/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { modelRoleSchema } from "../model/roleSchema.ts";

export const userCreateUserDTOSchema = z.object({
    "email": z.string(),
"name": z.string(),
"password": z.string(),
get "role"(){
                return modelRoleSchema
              }
    })