/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiErrorResponse } from "./api/ErrorResponse.ts";

export type DeleteUsersIdPathParams = {
    /**
     * @description User ID
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type DeleteUsersId200 = any;

/**
 * @description Bad Request
*/
export type DeleteUsersId400 = ApiErrorResponse;

/**
 * @description Internal Server Error
*/
export type DeleteUsersId500 = ApiErrorResponse;

export type DeleteUsersIdMutationResponse = DeleteUsersId200;

export type DeleteUsersIdMutation = {
    Response: DeleteUsersId200;
    PathParams: DeleteUsersIdPathParams;
    Errors: DeleteUsersId400 | DeleteUsersId500;
};