/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiErrorResponse } from "./api/ErrorResponse.ts";
import type { ModelUser } from "./model/User.ts";

export type GetUsersQueryParams = {
    /**
     * @description Maximum number of records
     * @default 2000
     * @type integer | undefined
    */
    take?: number;
    /**
     * @description Number of records to skip
     * @default 0
     * @type integer | undefined
    */
    skip?: number;
};

/**
 * @description OK
*/
export type GetUsers200 = ModelUser[];

/**
 * @description Bad Request
*/
export type GetUsers400 = ApiErrorResponse;

/**
 * @description Internal Server Error
*/
export type GetUsers500 = ApiErrorResponse;

export type GetUsersQueryResponse = GetUsers200;

export type GetUsersQuery = {
    Response: GetUsers200;
    QueryParams: GetUsersQueryParams;
    Errors: GetUsers400 | GetUsers500;
};