/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiErrorResponse } from "./api/ErrorResponse.ts";
import type { ModelUser } from "./model/User.ts";

export type GetUsersIdPathParams = {
    /**
     * @description User ID
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type GetUsersId200 = ModelUser;

/**
 * @description Internal Server Error
*/
export type GetUsersId500 = ApiErrorResponse;

export type GetUsersIdQueryResponse = GetUsersId200;

export type GetUsersIdQuery = {
    Response: GetUsersId200;
    PathParams: GetUsersIdPathParams;
    Errors: GetUsersId500;
};