/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiErrorResponse } from "./api/ErrorResponse.ts";
import type { UserCreateUserDTO } from "./user/CreateUserDTO.ts";

/**
 * @description OK
*/
export type PostUsers200 = any;

/**
 * @description Bad Request
*/
export type PostUsers400 = ApiErrorResponse;

/**
 * @description Internal Server Error
*/
export type PostUsers500 = ApiErrorResponse;

/**
 * @description User data
*/
export type PostUsersMutationRequest = UserCreateUserDTO;

export type PostUsersMutationResponse = PostUsers200;

export type PostUsersMutation = {
    Response: PostUsers200;
    Request: PostUsersMutationRequest;
    Errors: PostUsers400 | PostUsers500;
};