/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiErrorResponse } from "./api/ErrorResponse.ts";
import type { UserCreateUserDTO } from "./user/CreateUserDTO.ts";

export type PutUsersIdPathParams = {
    /**
     * @description User ID
     * @type string
    */
    id: string;
};

/**
 * @description OK
*/
export type PutUsersId200 = any;

/**
 * @description Bad Request
*/
export type PutUsersId400 = ApiErrorResponse;

/**
 * @description Internal Server Error
*/
export type PutUsersId500 = ApiErrorResponse;

/**
 * @description User data
*/
export type PutUsersIdMutationRequest = UserCreateUserDTO;

export type PutUsersIdMutationResponse = PutUsersId200;

export type PutUsersIdMutation = {
    Response: PutUsersId200;
    Request: PutUsersIdMutationRequest;
    PathParams: PutUsersIdPathParams;
    Errors: PutUsersId400 | PutUsersId500;
};