/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { modelRoleSchema } from "./roleSchema.ts";

export const modelUserSchema = z.object({
    "createdAt": z.optional(z.string()),
"email": z.optional(z.string()),
"id": z.optional(z.string()),
"name": z.optional(z.string()),
"password": z.optional(z.string()),
get "role"(){
                return modelRoleSchema.optional()
              },
"updatedAt": z.optional(z.string())
    })