/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiErrorResponseSchema } from "./api/errorResponseSchema.ts";

export const deleteUsersIdPathParamsSchema = z.object({
    "id": z.string().describe("User ID")
    })

/**
 * @description OK
 */
export const deleteUsersId200Schema = z.unknown()

/**
 * @description Bad Request
 */
export const deleteUsersId400Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description Internal Server Error
 */
export const deleteUsersId500Schema = z.lazy(() => apiErrorResponseSchema)

export const deleteUsersIdMutationResponseSchema = z.lazy(() => deleteUsersId200Schema)