/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiErrorResponseSchema } from "./api/errorResponseSchema.ts";
import { modelUserSchema } from "./model/userSchema.ts";

export const getUsersQueryParamsSchema = z.object({
    "take": z.coerce.number().int().default(2000).describe("Maximum number of records"),
"skip": z.coerce.number().int().default(0).describe("Number of records to skip")
    })

/**
 * @description OK
 */
export const getUsers200Schema = z.array(z.lazy(() => modelUserSchema))

/**
 * @description Bad Request
 */
export const getUsers400Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description Internal Server Error
 */
export const getUsers500Schema = z.lazy(() => apiErrorResponseSchema)

export const getUsersQueryResponseSchema = z.lazy(() => getUsers200Schema)