/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiErrorResponseSchema } from "./api/errorResponseSchema.ts";
import { modelUserSchema } from "./model/userSchema.ts";

export const getUsersIdPathParamsSchema = z.object({
    "id": z.string().describe("User ID")
    })

/**
 * @description OK
 */
export const getUsersId200Schema = z.lazy(() => modelUserSchema)

/**
 * @description Internal Server Error
 */
export const getUsersId500Schema = z.lazy(() => apiErrorResponseSchema)

export const getUsersIdQueryResponseSchema = z.lazy(() => getUsersId200Schema)