/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiErrorResponseSchema } from "./api/errorResponseSchema.ts";
import { userCreateUserDTOSchema } from "./user/createUserDTOSchema.ts";

/**
 * @description OK
 */
export const postUsers200Schema = z.unknown()

/**
 * @description Bad Request
 */
export const postUsers400Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description Internal Server Error
 */
export const postUsers500Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description User data
 */
export const postUsersMutationRequestSchema = z.lazy(() => userCreateUserDTOSchema)

export const postUsersMutationResponseSchema = z.lazy(() => postUsers200Schema)