/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { apiErrorResponseSchema } from "./api/errorResponseSchema.ts";
import { userCreateUserDTOSchema } from "./user/createUserDTOSchema.ts";

export const putUsersIdPathParamsSchema = z.object({
    "id": z.string().describe("User ID")
    })

/**
 * @description OK
 */
export const putUsersId200Schema = z.unknown()

/**
 * @description Bad Request
 */
export const putUsersId400Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description Internal Server Error
 */
export const putUsersId500Schema = z.lazy(() => apiErrorResponseSchema)

/**
 * @description User data
 */
export const putUsersIdMutationRequestSchema = z.lazy(() => userCreateUserDTOSchema)

export const putUsersIdMutationResponseSchema = z.lazy(() => putUsersId200Schema)