// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"

	"github.com/usesnipet/snipet/internal/mcp"
	"github.com/usesnipet/snipet/pkg/jsonx"
)

// NewMockIConnector creates a new instance of MockIConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIConnector {
	mock := &MockIConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIConnector is an autogenerated mock type for the IConnector type
type MockIConnector struct {
	mock.Mock
}

type MockIConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIConnector) EXPECT() *MockIConnector_Expecter {
	return &MockIConnector_Expecter{mock: &_m.Mock}
}

// CallTool provides a mock function for the type MockIConnector
func (_mock *MockIConnector) CallTool(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap, name string, args json.RawMessage) (*mcp.CallResult, error) {
	ret := _mock.Called(ctx, transport, config, name, args)

	if len(ret) == 0 {
		panic("no return value specified for CallTool")
	}

	var r0 *mcp.CallResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mcp.Transport, jsonx.JSONMap, string, json.RawMessage) (*mcp.CallResult, error)); ok {
		return returnFunc(ctx, transport, config, name, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mcp.Transport, jsonx.JSONMap, string, json.RawMessage) *mcp.CallResult); ok {
		r0 = returnFunc(ctx, transport, config, name, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.CallResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mcp.Transport, jsonx.JSONMap, string, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, transport, config, name, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConnector_CallTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallTool'
type MockIConnector_CallTool_Call struct {
	*mock.Call
}

// CallTool is a helper method to define mock.On call
//   - ctx context.Context
//   - transport mcp.Transport
//   - config jsonx.JSONMap
//   - name string
//   - args json.RawMessage
func (_e *MockIConnector_Expecter) CallTool(ctx any, transport any, config any, name any, args any) *MockIConnector_CallTool_Call {
	return &MockIConnector_CallTool_Call{Call: _e.mock.On("CallTool", ctx, transport, config, name, args)}
}

func (_c *MockIConnector_CallTool_Call) Run(run func(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap, name string, args json.RawMessage)) *MockIConnector_CallTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mcp.Transport
		if args[1] != nil {
			arg1 = args[1].(mcp.Transport)
		}
		var arg2 jsonx.JSONMap
		if args[2] != nil {
			arg2 = args[2].(jsonx.JSONMap)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 json.RawMessage
		if args[4] != nil {
			arg4 = args[4].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIConnector_CallTool_Call) Return(callResult *mcp.CallResult, err error) *MockIConnector_CallTool_Call {
	_c.Call.Return(callResult, err)
	return _c
}

func (_c *MockIConnector_CallTool_Call) RunAndReturn(run func(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap, name string, args json.RawMessage) (*mcp.CallResult, error)) *MockIConnector_CallTool_Call {
	_c.Call.Return(run)
	return _c
}

// ListTools provides a mock function for the type MockIConnector
func (_mock *MockIConnector) ListTools(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap) ([]mcp.RemoteTool, error) {
	ret := _mock.Called(ctx, transport, config)

	if len(ret) == 0 {
		panic("no return value specified for ListTools")
	}

	var r0 []mcp.RemoteTool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mcp.Transport, jsonx.JSONMap) ([]mcp.RemoteTool, error)); ok {
		return returnFunc(ctx, transport, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mcp.Transport, jsonx.JSONMap) []mcp.RemoteTool); ok {
		r0 = returnFunc(ctx, transport, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]mcp.RemoteTool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mcp.Transport, jsonx.JSONMap) error); ok {
		r1 = returnFunc(ctx, transport, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIConnector_ListTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTools'
type MockIConnector_ListTools_Call struct {
	*mock.Call
}

// ListTools is a helper method to define mock.On call
//   - ctx context.Context
//   - transport mcp.Transport
//   - config jsonx.JSONMap
func (_e *MockIConnector_Expecter) ListTools(ctx any, transport any, config any) *MockIConnector_ListTools_Call {
	return &MockIConnector_ListTools_Call{Call: _e.mock.On("ListTools", ctx, transport, config)}
}

func (_c *MockIConnector_ListTools_Call) Run(run func(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap)) *MockIConnector_ListTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mcp.Transport
		if args[1] != nil {
			arg1 = args[1].(mcp.Transport)
		}
		var arg2 jsonx.JSONMap
		if args[2] != nil {
			arg2 = args[2].(jsonx.JSONMap)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIConnector_ListTools_Call) Return(remoteTools []mcp.RemoteTool, err error) *MockIConnector_ListTools_Call {
	_c.Call.Return(remoteTools, err)
	return _c
}

func (_c *MockIConnector_ListTools_Call) RunAndReturn(run func(ctx context.Context, transport mcp.Transport, config jsonx.JSONMap) ([]mcp.RemoteTool, error)) *MockIConnector_ListTools_Call {
	_c.Call.Return(run)
	return _c
}
