/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteUsersIdMutationResponse, DeleteUsersIdPathParams, DeleteUsersId400, DeleteUsersId500 } from "../types/DeleteUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteUsersId } from "../client/deleteUsersId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteUsersIdMutationKey = () => [{ url: '/users/:id' }] as const

export type DeleteUsersIdMutationKey = ReturnType<typeof deleteUsersIdMutationKey>

export function deleteUsersIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteUsersIdMutationKey()
        return mutationOptions<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, {id: DeleteUsersIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteUsersId(id, config)
          },
        })

}

/**
 * @description Delete a user by ID.
 * @summary Delete user by ID
 * {@link /users/:id}
 */
export function useDeleteUsersId<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, {id: DeleteUsersIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteUsersIdMutationKey()

          const baseOptions = deleteUsersIdMutationOptions(config) as UseMutationOptions<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, {id: DeleteUsersIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, {id: DeleteUsersIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteUsersIdMutationResponse, ResponseErrorConfig<DeleteUsersId400 | DeleteUsersId500>, {id: DeleteUsersIdPathParams["id"]}, TContext>
      
}