/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUsersIdQueryResponse, GetUsersIdPathParams, GetUsersId500 } from "../types/GetUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getUsersId } from "../client/getUsersId.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUsersIdQueryKey = (id: GetUsersIdPathParams["id"] | undefined) => [{ url: '/users/:id', params: {id:id} }] as const

export type GetUsersIdQueryKey = ReturnType<typeof getUsersIdQueryKey>

export function getUsersIdQueryOptions(id: GetUsersIdPathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUsersIdQueryKey(id)
        return queryOptions<GetUsersIdQueryResponse, ResponseErrorConfig<GetUsersId500>, GetUsersIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return getUsersId(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Return a user by ID.
 * @summary Find user by ID
 * {@link /users/:id}
 */
export function useGetUsersId<TData = GetUsersIdQueryResponse, TQueryData = GetUsersIdQueryResponse, TQueryKey extends QueryKey = GetUsersIdQueryKey>(id: GetUsersIdPathParams["id"] | undefined, options: 
{
  query?: Partial<QueryObserverOptions<GetUsersIdQueryResponse, ResponseErrorConfig<GetUsersId500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUsersIdQueryKey(id)
         

         const query = useQuery({
          ...getUsersIdQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUsersId500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}