/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUsersIdQueryResponse, GetUsersIdPathParams, GetUsersId500 } from "../types/GetUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getUsersId } from "../client/getUsersId.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getUsersIdSuspenseQueryKey = (id: GetUsersIdPathParams["id"] | undefined) => [{ url: '/users/:id', params: {id:id} }] as const

export type GetUsersIdSuspenseQueryKey = ReturnType<typeof getUsersIdSuspenseQueryKey>

export function getUsersIdSuspenseQueryOptions(id: GetUsersIdPathParams["id"] | undefined, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUsersIdSuspenseQueryKey(id)
        return queryOptions<GetUsersIdQueryResponse, ResponseErrorConfig<GetUsersId500>, GetUsersIdQueryResponse, typeof queryKey>({
         enabled: !!(id),
         queryKey,
         queryFn: async ({ signal }) => {
            return getUsersId(id!, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Return a user by ID.
 * @summary Find user by ID
 * {@link /users/:id}
 */
export function useGetUsersIdSuspense<TData = GetUsersIdQueryResponse, TQueryKey extends QueryKey = GetUsersIdSuspenseQueryKey>(id: GetUsersIdPathParams["id"] | undefined, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetUsersIdQueryResponse, ResponseErrorConfig<GetUsersId500>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUsersIdSuspenseQueryKey(id)
         

         const query = useSuspenseQuery({
          ...getUsersIdSuspenseQueryOptions(id, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetUsersId500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}