/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUsersQueryResponse, GetUsersQueryParams, GetUsers400, GetUsers500 } from "../types/GetUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getUsers } from "../client/getUsers.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUsersQueryKey = (params?: GetUsersQueryParams) => [{ url: '/users' }, ...(params ? [params] : [])] as const

export type GetUsersQueryKey = ReturnType<typeof getUsersQueryKey>

export function getUsersQueryOptions(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getUsersQueryKey(params)
        return queryOptions<GetUsersQueryResponse, ResponseErrorConfig<GetUsers400 | GetUsers500>, GetUsersQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getUsers(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Return a list of users with pagination and optional filters.
 * @summary Find all users
 * {@link /users}
 */
export function useGetUsers<TData = GetUsersQueryResponse, TQueryData = GetUsersQueryResponse, TQueryKey extends QueryKey = GetUsersQueryKey>(params?: GetUsersQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetUsersQueryResponse, ResponseErrorConfig<GetUsers400 | GetUsers500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getUsersQueryKey(params)
         

         const query = useQuery({
          ...getUsersQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetUsers400 | GetUsers500>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}