/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PostUsersMutationRequest, PostUsersMutationResponse, PostUsers400, PostUsers500 } from "../types/PostUsers.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { postUsers } from "../client/postUsers.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postUsersMutationKey = () => [{ url: '/users' }] as const

export type PostUsersMutationKey = ReturnType<typeof postUsersMutationKey>

export function postUsersMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostUsersMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postUsersMutationKey()
        return mutationOptions<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, {data: PostUsersMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postUsers(data, config)
          },
        })

}

/**
 * @description Create a new user.
 * @summary Create user
 * {@link /users}
 */
export function usePostUsers<TContext>(options: 
{
  mutation?: UseMutationOptions<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, {data: PostUsersMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostUsersMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postUsersMutationKey()

          const baseOptions = postUsersMutationOptions(config) as UseMutationOptions<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, {data: PostUsersMutationRequest}, TContext>
          

          return useMutation<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, {data: PostUsersMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostUsersMutationResponse, ResponseErrorConfig<PostUsers400 | PostUsers500>, {data: PostUsersMutationRequest}, TContext>
      
}