/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PutUsersIdMutationRequest, PutUsersIdMutationResponse, PutUsersIdPathParams, PutUsersId400, PutUsersId500 } from "../types/PutUsersId.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { putUsersId } from "../client/putUsersId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putUsersIdMutationKey = () => [{ url: '/users/:id' }] as const

export type PutUsersIdMutationKey = ReturnType<typeof putUsersIdMutationKey>

export function putUsersIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PutUsersIdMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = putUsersIdMutationKey()
        return mutationOptions<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, {id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return putUsersId(id, data, config)
          },
        })

}

/**
 * @description Update a user by ID.
 * @summary Update user by ID
 * {@link /users/:id}
 */
export function usePutUsersId<TContext>(options: 
{
  mutation?: UseMutationOptions<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, {id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PutUsersIdMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? putUsersIdMutationKey()

          const baseOptions = putUsersIdMutationOptions(config) as UseMutationOptions<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, {id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest}, TContext>
          

          return useMutation<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, {id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PutUsersIdMutationResponse, ResponseErrorConfig<PutUsersId400 | PutUsersId500>, {id: PutUsersIdPathParams["id"], data: PutUsersIdMutationRequest}, TContext>
      
}