/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ModelRole } from "../model/Role.ts";

export type UserCreateUserDTO = {
    /**
     * @type string
    */
    email: string;
    /**
     * @type string
    */
    name: string;
    /**
     * @type string
    */
    password: string;
    role: ModelRole;
};