/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";

export const apiErrorResponseSchema = z.object({
    "error": z.optional(z.string()),
"statusCode": z.optional(z.int()),
"statusText": z.optional(z.string())
    })